context:
  testimonials:
    - content: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos dolor alias accusamus blanditiis sunt maiores, expedita facilis placeat natus, nesciunt architecto, voluptates quidem itaque explicabo, assumenda necessitatibus quod nobis ut.
      citation: Jane Doe
    - content: Quos dolor alias accusamus blanditiis sunt maiores, expedita facilis placeat natus, nesciunt architecto, voluptates quidem itaque explicabo, assumenda necessitatibus quod nobis ut. Lorem ipsum dolor sit amet, consectetur adipisicing elit.
      citation: Dr. Makebelieve
    - content: Cras ornare posuere nisl, eu viverra enim dapibus vel. Morbi egestas, arcu non sollicitudin pellentesque, nibh lorem tristique sapien, nec facilisis mi nulla et nisi.
      citation: Mr. Pretend
    - content: Maecenas est magna, imperdiet in dui in, tempor elementum massa. Fusce sit amet tortor mauris. Ut libero magna, efficitur at ante eu, dictum dictum dolor.
      citation: John Doe
    - content: Ut quis turpis rutrum, blandit metus et, accumsan velit. Etiam lacus risus, mollis quis finibus vel, sagittis a justo. Quos dolor alias accusamus blanditiis sunt maiores.
      citation: Ms. Example


